AllCops:
  Exclude:
    - "db/**/*"

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  AllowedMethods:
    - change
    - not_change

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
