version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - app-bundle:/usr/local/bundle
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: sinatra_app_development
    ports:
      - 4567:4567
    depends_on:
      db:
        condition: service_healthy
    working_dir: /workspace
  db:
    image: mysql
    platform: linux/x86_64
    volumes:
      - db-data:/var/lib/mysql
      - ./db/entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3906:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  db-data:
  app-bundle:
