openapi: "3.1.0"
info:
  title: acme api
  version: "1.0"
servers:
  - url: "http://localhost:4567"
paths:
  "/_healthcheck":
    get:
      tags:
        - healthcheck
      summary: healthcheck
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: ok
                required:
                  - msg
