openapi: "3.1.0"
info:
  title: acme api
  version: "1.0"
servers:
  - url: "http://localhost:4567"
paths:
  /_healthcheck:
    get:
      tags:
        - healthcheck
      summary: healthcheck
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: ok
                required:
                  - msg
  /users:
    get:
      tags:
        - user
      summary: show user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: UnAuthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorUnauthorized"

components:
  schemas:
    ErrorUnauthorized:
      title: Authorization failed
      type: object
      properties:
        msg:
          description: Reason for error
          type: string
          example: unauthorized
    User:
      title: User
      type: object
      properties:
        name:
          description: name
          type: string
          example: shuntagami
          maxLength: 20
      required:
        - name
