name: API

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  job_for_api:
    name: test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        env:
          DOCKER_BUILDKIT: 1
        run: |
          make build
      - name: Setup db
        run: |
          docker compose run --rm app bundle exec rake db:setup RACK_ENV="test"
      - name: Run lint
        run: |
          make lint
      - name: Run test
        run: |
          make api_test
